public class CCT_Kriya_Constants {
    /***
@author Sneha
@description constant
@date 14/04/2023
**/
    public static final string MIDTERMCYCLE = 'Mid_Term_Start_Date';
    public static final string ANNUALTERMCYCLE = 'Annual_Start_Date';
    public static final string MIDTERMAPPRAISEE_TO_APPRAISER= 'Mid_Term_Appraisee_To_Appraiser';
    public static final string ANNUALTERMAPPRAISEE_TO_APPRAISER = 'Annual_Appraisee_To_Appraiser';
    public static final string ANNUAL_APPRAISER = 'Annual_Appraiser';
    public static final string MIDTERM_APPRAISER = 'Mid_Term_Appraiser';
    public static final string ANNUAL_FINAL_RATING_END_DATE = 'Annual_Final_Rating_End_Date';
    public static final string MIDTERM_FINAL_RATING_END_DATE = 'Mid_Term_Final_Rating_End_Date';
    public static final string INITIATED_STATUS = 'Initiated';
    public static final string NOTINITIATED_STATUS = 'Not Initiated';
    public static final string AUTOSUBMITTED_STATUS = 'Auto Submitted';
    public static final string RECORDTYPE = 'Appraisal_Form';
    public static final string SUBMITTED_STATUS = 'Submitted';
    public static final string ANNUAL_3 = 'Annual_3';
    public static final string Feedback_Requested = 'Feedback Requested';
    public static final string RECORDTYPES = 'Feedback_Form'; 
    public static final string AppraiseeTasks = 'AppraiseeTasks';
    
}